MAKEFILE
# A simple Makefile for CPSC 350
# Assumes the following directory hierarchy:
# Assignment GameOfLife
# 	src
#       include

#this Makefile goes in the src directory

#change this to the correct assignment #
EXECUTABLE := GameOfLife1

# the source files to be built
SOURCES := *.cpp, *.h

#stuff you don't need to worry about
INCLUDES := -I ../include
EXT := exe
CC := g++

all:
	$(CC) $(INCLUDES) $(SOURCES) -o $(EXECUTABLE).$(EXT)

realclean:
	find . -type f -name "*.o" -exec rm '{}' \;
	#removes .o files
	find . -type f -name "*.exe" -exec rm '{}' \;
	#removes exe file

# this line required by make - don't delete
